### ISSUE TITLE
EPICS_AD_Viewer conflicts with HDF5_Viewer

### ISSUE THREAD

**Issue by kematusik** [areaDetector/ADViewers#18] opened 2020-11-25 18:06 UTC
We recently became interested in using an[ HDF5 Viewer (v0.13.0)](https://github.com/paulscherrerinstitute/ch.psi.imagej.hdf5/releases) that supports opening very large HDF files. Using the latest version of [ImageJ for Linux](https://imagej.nih.gov/ij/download.html) bundled with Java 1.8.0_172, the HDF viewer itself compiles and works normally. As soon as the EPICS_areaDetector folder is added into ImageJ/plugins, the following error appears when launching the HDF viewer:
ImageJ 1.53e; Java 1.8.0_172 [64-bit]; Linux 4.15.0-123-generic; 87MB of 85867MB (<1%)
java.lang.NoSuchMethodError: org.slf4j.Logger.trace(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)V
	at hdf.object.FileFormat.<init>(FileFormat.java:315)
	at hdf.object.h5.H5File.<init>(H5File.java:174)
	at hdf.object.h5.H5File.<init>(H5File.java:127)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at hdf.object.FileFormat.<clinit>(FileFormat.java:228)
	at ch.psi.imagej.hdf5.HDF5Reader.open(HDF5Reader.java:82)
	at ch.psi.imagej.hdf5.HDF5Reader.open(HDF5Reader.java:51)
	at ch.psi.imagej.hdf5.HDF5Reader.run(HDF5Reader.java:36)
	at ij.IJ.runUserPlugIn(IJ.java:240)
	at ij.IJ.runPlugIn(IJ.java:203)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)

When the EPICS_areaDetector folder is removed, the HDF Viewer goes back to working normally. I'm  using Ubuntu 16.04.1 64-bit with kernel 4.15.0-123-generic.

**Comment by MarkRivers** [comment] 2020-12-01 13:18
This problem appears to occur when different plugins use different versions of the slj4 logging module.  I have seen that error previously.

I am using that same HDF5 plugin (0.13.0) on my Windows systems, and it does not have a conflict with the areaDetector viewers.  I have not tried it with Linux yet.

> Using the latest version of ImageJ for Linux bundled with Java 1.8.0_172, the HDF viewer itself compiles and works normally.

This sounds like you are building the HDF5 plugin from source?  I am just using the .jar files provided on the Web page you link to above.  Did you try that?

**Comment by MarkRivers** [comment] 2020-12-01 13:31
> I am using that same HDF5 plugin (0.13.0) on my Windows systems, and it does not have a conflict with the areaDetector viewers. I have not tried it with Linux yet.

My apologies, I just found that statement was not true.  In order to get the HDF5 plugin to work I had created a fresh install of ImageJ on Windows, and had not yet installed the areaDetector viewers.  Once I did that then I get the same error as you when trying to run the HDF5 plugin.

One solution would be to have 2 installations of ImageJ, one that has areaDetector viewers, and another with the HDF5 viewer.  But that is not convenient. 

I don't think the ADViewers Java code itself uses slj4.  However, when I search for "logging" in that directory I get this:
```
corvette:areaDetector/ADViewers/ImageJ>git grep logging
Binary file EPICS_areaDetector/epics-pvaccess-5.1.5.jar matches
Binary file EPICS_areaDetector/jca-2.4.5.jar matches
```
So it looks like perhaps epics-pvaccess or jca is using a version of the slj4 logging code that is incompatible with the version used in the HDF5 plugin.  This is a question for the EPICS Java experts.

**Comment by MarkRivers** [comment] 2020-12-01 13:42
I have opened an issue for this in the epicsCoreJava repository: 
https://github.com/epics-base/epicsCoreJava/issues/114

**Comment by MarkRivers** [comment] 2020-12-01 15:09
I figured out the conflict.  
```
corvette:ADViewers/ImageJ/EPICS_areaDetector>grep slf4j *
Binary file NetCDF_.jar matches
```
The problem is that NetCDF_.jar is using a version of slf4j that is incompatible with the version in the HDF5 plugin.

The solution is easy, just delete NetCDF_.jar from the ADViewers/epicsAreaDetector directory. I tried that and it works.

Note that the NetCDF_.jar file does not really belong in ADViewers.  I put it there as a convenience for users to be able to read netCDF files written by the areDetector NDFileNetCDF plugin.  But it can be downloaded separately for those who want it.

This does seem to mean that one cannot use the netCDF and HDF5 plugins in the same installation of ImageJ.  That is unfortunate, since I use both for my tomography beamline at the APS.

Perhaps that can be fixed by changing the search order of ImageJ, so that it finds the HDF5 plugin first, and uses the more recent version of slf4j?

**Comment by MarkRivers** [comment] 2020-12-19 15:11
I am attempting to find the source code for the netCDF plugin.  I have made contact with the original author.  He does not have the source code any more, but suggested that I contact the University of Freiburg where the .jar file is hosted.  I am trying that.

**Comment by kematusik** [comment] 2020-12-21 16:43
I want to confirm that deleting NetCDF_.jar did work for me; thanks so much for the prompt response.

**Comment by MarkRivers** [comment] 2020-12-22 22:08
I am closing this issue.  I am pursuing the source code for the netCDF ImageJ plugin, but so far I have not had success.

**Closed as completed by MarkRivers** 2020-12-22 22:08 UTC
